### ISSUE TITLE
Add search UI to top of connections page

### ISSUE THREAD

**Issue by clas-web** [clas-web/unc-charlotte-project-mosaic-theme#5]
The connections page templates should include the same search UI as on other connections sites, compare:
https://pages.uncc.edu/connections/
https://projectmosaic.uncc.edu/connections/

**Comment by clas-web** [comment]
This could also be implemented as shortcode and/or widget

**Comment by marpa** [comment]
If shortcode is created for this search UI, then it should be added to:
https://projectmosaic.uncc.edu/connections/

**Comment by atrus1701** [comment]
0cac872dee3fc2656ef4190bd3753a02db3a81c4
